version: '3.8'
services:
    php-apache-environment:
        container_name: zesty_app
        build:
            context: ./
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./:/var/www/html/
        ports:
            - 8000:80
    db:
        container_name: zesty_db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: zesty
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
        ports:
            - "9906:3306"